parameters:
    ek_stripe_payment.contract.firewall.class: EdouardKombo\EkStripePaymentBundle\Contract\FirewallContract     
    ek_stripe_payment.contract.setget.class: EdouardKombo\EkStripePaymentBundle\Contract\SetGetContract
    ek_stripe_payment.contract.communication.class: EdouardKombo\EkStripePaymentBundle\Contract\CommunicationContract      
    ek_stripe_payment.helper.stripe.class: EdouardKombo\EkStripePaymentBundle\Helper\StripeHelper
    ek_stripe_payment.controller.stripe.class: EdouardKombo\EkStripePaymentBundle\Controller\StripeController     

services:
    ek_stripe_payment.contract.firewall:
        class: %ek_stripe_payment.contract.firewall.class%
        
    ek_stripe_payment.contract.setget:
        class: %ek_stripe_payment.contract.setget.class%
        arguments:
            - @ek_stripe_payment.contract.firewall
            
    ek_stripe_payment.controller.stripe:
        class: %ek_stripe_payment.controller.stripe.class%
        arguments:
            - @service_container
    
    ek_stripe_payment.helper.stripe:
        class: %ek_stripe_payment.helper.stripe.class%
        arguments:
            - @ek_stripe_payment.contract.setget
            - %ek_stripe_payment.params%
            - @ek_stripe_payment.contract.firewall
            - @security.context              
            - @doctrine.orm.entity_manager          
            
    ek_stripe_payment.contract.communication:
        class: %ek_stripe_payment.contract.communication.class%
        arguments:
            - @ek_stripe_payment.helper.stripe             
